-- Landmarks: park and badge catalogs
--
-- All 63 US national parks plus the starter badge set. This is reference data
-- the app cannot run without, so it ships as a migration rather than a seed
-- file, which keeps every environment identical. Safe to re-run.
--
-- Coordinates are approximate park centroids, good enough to anchor a map pin
-- and to sort "parks near me"; they are not visitor center addresses.

insert into public.parks (slug, name, description, location, state_codes, is_verified)
values
  ('acadia', 'Acadia', 'Granite peaks and rocky Atlantic coastline on Mount Desert Island.',
   extensions.st_makepoint(-68.21, 44.35)::extensions.geography, '{ME}', true),
  ('american-samoa', 'National Park of American Samoa', 'Rainforest, coral reefs and volcanic ridges in the South Pacific.',
   extensions.st_makepoint(-170.68, -14.25)::extensions.geography, '{AS}', true),
  ('arches', 'Arches', 'Over 2,000 natural sandstone arches above the Colorado River.',
   extensions.st_makepoint(-109.59, 38.73)::extensions.geography, '{UT}', true),
  ('badlands', 'Badlands', 'Layered rock spires and the largest mixed-grass prairie in the system.',
   extensions.st_makepoint(-102.34, 43.85)::extensions.geography, '{SD}', true),
  ('big-bend', 'Big Bend', 'Chihuahuan Desert, the Chisos Mountains and a long bend in the Rio Grande.',
   extensions.st_makepoint(-103.25, 29.25)::extensions.geography, '{TX}', true),
  ('biscayne', 'Biscayne', 'Mangrove shoreline, turquoise bay and living coral reefs.',
   extensions.st_makepoint(-80.08, 25.65)::extensions.geography, '{FL}', true),
  ('black-canyon-of-the-gunnison', 'Black Canyon of the Gunnison', 'A gorge so steep and narrow that parts see almost no sunlight.',
   extensions.st_makepoint(-107.72, 38.57)::extensions.geography, '{CO}', true),
  ('bryce-canyon', 'Bryce Canyon', 'Amphitheaters of orange hoodoos carved by frost and rain.',
   extensions.st_makepoint(-112.18, 37.57)::extensions.geography, '{UT}', true),
  ('canyonlands', 'Canyonlands', 'Mesas, buttes and canyons split into districts by two rivers.',
   extensions.st_makepoint(-109.93, 38.20)::extensions.geography, '{UT}', true),
  ('capitol-reef', 'Capitol Reef', 'The Waterpocket Fold, a hundred-mile wrinkle in the earth.',
   extensions.st_makepoint(-111.17, 38.20)::extensions.geography, '{UT}', true),
  ('carlsbad-caverns', 'Carlsbad Caverns', 'A vast decorated cave chamber beneath the Guadalupe Mountains.',
   extensions.st_makepoint(-104.44, 32.17)::extensions.geography, '{NM}', true),
  ('channel-islands', 'Channel Islands', 'Five islands of sea caves, kelp forests and endemic species.',
   extensions.st_makepoint(-119.42, 34.01)::extensions.geography, '{CA}', true),
  ('congaree', 'Congaree', 'One of the tallest deciduous forests left in North America.',
   extensions.st_makepoint(-80.78, 33.78)::extensions.geography, '{SC}', true),
  ('crater-lake', 'Crater Lake', 'The deepest lake in the country, filling a collapsed volcano.',
   extensions.st_makepoint(-122.10, 42.94)::extensions.geography, '{OR}', true),
  ('cuyahoga-valley', 'Cuyahoga Valley', 'Waterfalls, towpath trail and farmland along a winding river.',
   extensions.st_makepoint(-81.55, 41.24)::extensions.geography, '{OH}', true),
  ('death-valley', 'Death Valley', 'The lowest, driest and hottest place in North America.',
   extensions.st_makepoint(-117.08, 36.51)::extensions.geography, '{CA,NV}', true),
  ('denali', 'Denali', 'Six million acres of subarctic wilderness under the highest peak in North America.',
   extensions.st_makepoint(-150.50, 63.33)::extensions.geography, '{AK}', true),
  ('dry-tortugas', 'Dry Tortugas', 'A nineteenth-century fort on remote islands 70 miles west of Key West.',
   extensions.st_makepoint(-82.87, 24.63)::extensions.geography, '{FL}', true),
  ('everglades', 'Everglades', 'A slow-moving river of grass and the largest subtropical wilderness in the US.',
   extensions.st_makepoint(-80.93, 25.32)::extensions.geography, '{FL}', true),
  ('gates-of-the-arctic', 'Gates of the Arctic', 'No roads and no trails, entirely north of the Arctic Circle.',
   extensions.st_makepoint(-153.30, 67.78)::extensions.geography, '{AK}', true),
  ('gateway-arch', 'Gateway Arch', 'The stainless steel arch on the St. Louis riverfront.',
   extensions.st_makepoint(-90.19, 38.63)::extensions.geography, '{MO}', true),
  ('glacier', 'Glacier', 'Carved peaks, alpine lakes and the Going-to-the-Sun Road.',
   extensions.st_makepoint(-114.00, 48.80)::extensions.geography, '{MT}', true),
  ('glacier-bay', 'Glacier Bay', 'Tidewater glaciers calving into a cold, whale-filled bay.',
   extensions.st_makepoint(-137.00, 58.50)::extensions.geography, '{AK}', true),
  ('grand-canyon', 'Grand Canyon', 'A mile deep and two billion years of rock exposed by the Colorado River.',
   extensions.st_makepoint(-112.14, 36.06)::extensions.geography, '{AZ}', true),
  ('grand-teton', 'Grand Teton', 'An abrupt mountain front rising above the Snake River valley.',
   extensions.st_makepoint(-110.80, 43.73)::extensions.geography, '{WY}', true),
  ('great-basin', 'Great Basin', 'Ancient bristlecone pines, a glacier and some of the darkest night skies.',
   extensions.st_makepoint(-114.30, 38.98)::extensions.geography, '{NV}', true),
  ('great-sand-dunes', 'Great Sand Dunes', 'The tallest dunes in North America against the Sangre de Cristos.',
   extensions.st_makepoint(-105.51, 37.73)::extensions.geography, '{CO}', true),
  ('great-smoky-mountains', 'Great Smoky Mountains', 'Blue ridges, old-growth forest and the most visited park in the system.',
   extensions.st_makepoint(-83.53, 35.68)::extensions.geography, '{TN,NC}', true),
  ('guadalupe-mountains', 'Guadalupe Mountains', 'A fossil reef holding the four highest peaks in Texas.',
   extensions.st_makepoint(-104.87, 31.92)::extensions.geography, '{TX}', true),
  ('haleakala', 'Haleakala', 'A vast volcanic summit basin above the clouds on Maui.',
   extensions.st_makepoint(-156.17, 20.72)::extensions.geography, '{HI}', true),
  ('hawaii-volcanoes', 'Hawaii Volcanoes', 'Kilauea and Mauna Loa, two of the most active volcanoes on earth.',
   extensions.st_makepoint(-155.20, 19.38)::extensions.geography, '{HI}', true),
  ('hot-springs', 'Hot Springs', 'Thermal springs and historic bathhouses in the Ouachita Mountains.',
   extensions.st_makepoint(-93.05, 34.51)::extensions.geography, '{AR}', true),
  ('indiana-dunes', 'Indiana Dunes', 'Dunes, wetlands and prairie along the south shore of Lake Michigan.',
   extensions.st_makepoint(-87.05, 41.63)::extensions.geography, '{IN}', true),
  ('isle-royale', 'Isle Royale', 'A remote Lake Superior island of wolves, moose and no cars.',
   extensions.st_makepoint(-88.55, 48.10)::extensions.geography, '{MI}', true),
  ('joshua-tree', 'Joshua Tree', 'Where the Mojave and Colorado deserts meet, full of boulders and yuccas.',
   extensions.st_makepoint(-115.90, 33.79)::extensions.geography, '{CA}', true),
  ('katmai', 'Katmai', 'Brown bears fishing at Brooks Falls and a valley of volcanic ash.',
   extensions.st_makepoint(-155.00, 58.50)::extensions.geography, '{AK}', true),
  ('kenai-fjords', 'Kenai Fjords', 'The Harding Icefield and the glaciers spilling out of it.',
   extensions.st_makepoint(-149.65, 59.92)::extensions.geography, '{AK}', true),
  ('kings-canyon', 'Kings Canyon', 'Giant sequoia groves above one of the deepest canyons in the country.',
   extensions.st_makepoint(-118.55, 36.80)::extensions.geography, '{CA}', true),
  ('kobuk-valley', 'Kobuk Valley', 'Arctic sand dunes and the caribou migration crossing the Kobuk River.',
   extensions.st_makepoint(-159.12, 67.33)::extensions.geography, '{AK}', true),
  ('lake-clark', 'Lake Clark', 'Volcanoes, turquoise lakes and coastal bear country.',
   extensions.st_makepoint(-153.42, 60.97)::extensions.geography, '{AK}', true),
  ('lassen-volcanic', 'Lassen Volcanic', 'Hydrothermal basins and all four types of volcano in one park.',
   extensions.st_makepoint(-121.51, 40.49)::extensions.geography, '{CA}', true),
  ('mammoth-cave', 'Mammoth Cave', 'The longest known cave system in the world.',
   extensions.st_makepoint(-86.10, 37.18)::extensions.geography, '{KY}', true),
  ('mesa-verde', 'Mesa Verde', 'Ancestral Puebloan cliff dwellings built into canyon walls.',
   extensions.st_makepoint(-108.49, 37.18)::extensions.geography, '{CO}', true),
  ('mount-rainier', 'Mount Rainier', 'A glaciated stratovolcano ringed by subalpine wildflower meadows.',
   extensions.st_makepoint(-121.75, 46.85)::extensions.geography, '{WA}', true),
  ('new-river-gorge', 'New River Gorge', 'Whitewater, climbing cliffs and a steel arch bridge over an old river.',
   extensions.st_makepoint(-81.06, 37.93)::extensions.geography, '{WV}', true),
  ('north-cascades', 'North Cascades', 'Jagged peaks and more glaciers than anywhere outside Alaska.',
   extensions.st_makepoint(-121.20, 48.70)::extensions.geography, '{WA}', true),
  ('olympic', 'Olympic', 'Rainforest, glaciated peaks and wild Pacific coast in one park.',
   extensions.st_makepoint(-123.60, 47.80)::extensions.geography, '{WA}', true),
  ('petrified-forest', 'Petrified Forest', 'Fossilized wood and the banded badlands of the Painted Desert.',
   extensions.st_makepoint(-109.78, 35.07)::extensions.geography, '{AZ}', true),
  ('pinnacles', 'Pinnacles', 'Rock spires from an ancient volcano, and California condors overhead.',
   extensions.st_makepoint(-121.16, 36.48)::extensions.geography, '{CA}', true),
  ('redwood', 'Redwood', 'The tallest trees on earth in coastal fog belt forest.',
   extensions.st_makepoint(-124.00, 41.30)::extensions.geography, '{CA}', true),
  ('rocky-mountain', 'Rocky Mountain', 'Tundra above treeline and Trail Ridge Road across the divide.',
   extensions.st_makepoint(-105.58, 40.40)::extensions.geography, '{CO}', true),
  ('saguaro', 'Saguaro', 'Dense forests of the giant cactus on both sides of Tucson.',
   extensions.st_makepoint(-110.50, 32.25)::extensions.geography, '{AZ}', true),
  ('sequoia', 'Sequoia', 'General Sherman and the largest trees on earth by volume.',
   extensions.st_makepoint(-118.68, 36.43)::extensions.geography, '{CA}', true),
  ('shenandoah', 'Shenandoah', 'Skyline Drive along the crest of the Blue Ridge Mountains.',
   extensions.st_makepoint(-78.35, 38.53)::extensions.geography, '{VA}', true),
  ('theodore-roosevelt', 'Theodore Roosevelt', 'Painted badlands and bison along the Little Missouri River.',
   extensions.st_makepoint(-103.54, 46.97)::extensions.geography, '{ND}', true),
  ('virgin-islands', 'Virgin Islands', 'White sand beaches, reefs and sugar plantation ruins on St. John.',
   extensions.st_makepoint(-64.73, 18.33)::extensions.geography, '{VI}', true),
  ('voyageurs', 'Voyageurs', 'Interconnected lakes best seen by boat, and northern lights in winter.',
   extensions.st_makepoint(-92.88, 48.50)::extensions.geography, '{MN}', true),
  ('white-sands', 'White Sands', 'The world''s largest gypsum dune field, blindingly white.',
   extensions.st_makepoint(-106.17, 32.78)::extensions.geography, '{NM}', true),
  ('wind-cave', 'Wind Cave', 'A dense cave of rare boxwork formations under open prairie.',
   extensions.st_makepoint(-103.48, 43.57)::extensions.geography, '{SD}', true),
  ('wrangell-st-elias', 'Wrangell-St. Elias', 'The largest national park, bigger than Switzerland.',
   extensions.st_makepoint(-142.00, 61.00)::extensions.geography, '{AK}', true),
  ('yellowstone', 'Yellowstone', 'The first national park, sitting on a supervolcano full of geysers.',
   extensions.st_makepoint(-110.50, 44.60)::extensions.geography, '{WY,MT,ID}', true),
  ('yosemite', 'Yosemite', 'Granite walls, waterfalls and sequoias in the Sierra Nevada.',
   extensions.st_makepoint(-119.50, 37.83)::extensions.geography, '{CA}', true),
  ('zion', 'Zion', 'Red sandstone cliffs and the Virgin River narrows.',
   extensions.st_makepoint(-113.05, 37.30)::extensions.geography, '{UT}', true)
on conflict (slug) do nothing;

insert into public.badges (slug, name, description, icon, criteria)
values
  ('first-light', 'First Light', 'Shared your first park photo.', 'camera',
   '{"type": "post_count", "count": 1}'::jsonb),
  ('regular', 'Regular', 'Shared 10 park photos.', 'photo.stack',
   '{"type": "post_count", "count": 10}'::jsonb),
  ('prolific', 'Prolific', 'Shared 50 park photos.', 'sparkles',
   '{"type": "post_count", "count": 50}'::jsonb),
  ('five-parks', 'Five Parks', 'Posted from 5 different national parks.', 'tree',
   '{"type": "park_count", "count": 5}'::jsonb),
  ('ten-parks', 'Ten Parks', 'Posted from 10 different national parks.', 'mountain.2',
   '{"type": "park_count", "count": 10}'::jsonb),
  ('quarter-century', 'Quarter Century', 'Posted from 25 different national parks.', 'trophy',
   '{"type": "park_count", "count": 25}'::jsonb),
  ('all-sixty-three', 'All Sixty-Three', 'Posted from every national park.', 'crown',
   '{"type": "park_count", "count": 63}'::jsonb),
  ('road-trip', 'Road Trip', 'Posted from parks in 5 different states.', 'car',
   '{"type": "state_count", "count": 5}'::jsonb),
  ('coast-to-coast', 'Coast to Coast', 'Posted from parks in 15 different states.', 'map',
   '{"type": "state_count", "count": 15}'::jsonb)
on conflict (slug) do nothing;
